language: d
sudo: false

env:
  global:
    - DUB_BUILD_TYPE=unittest-cov

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.096.0
    - d: ldc-1.25.1
  allow_failures:
    - d: dmd-nightly

addons:
  apt:
    packages:
      - libzmq3-dev

script:
  - export DC=${DC}
  - ./ci.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
